<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>PhoneStoreAdmin</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x86;x64;ARM64</Platforms>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PlatformTarget>x64</PlatformTarget>
    <UseWinUI>true</UseWinUI>
    <EnableMsixTooling>true</EnableMsixTooling>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Theme\Colors.xaml" />
    <None Remove="View\Controls\InvoiceDialog.xaml" />
    <None Remove="View\Controls\LoadingOverlay.xaml" />
    <None Remove="View\InvoicePage.Xaml" />
    <None Remove="View\PurchaseOrdersPage.xaml" />
  </ItemGroup>
  <ItemGroup>
    <Page Remove="LoginWindow.xaml" />
  </ItemGroup>
	
  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <!-- Logo assets -->
    <Content Include="Assets\logo_name.png" />
    <Content Include="Assets\logo.scale-100.png" />
    <Content Include="Assets\logo.scale-125.png" />
    <Content Include="Assets\logo.scale-150.png" />
    <Content Include="Assets\logo.scale-200.png" />
    <Content Include="Assets\logo.scale-400.png" />
    
    <!-- Splash Screen assets with transparent background -->
  </ItemGroup>

  <ItemGroup>
    <Manifest Include="$(ApplicationManifest)" />
  </ItemGroup>

  <ItemGroup Condition="'$(DisableMsixProjectCapabilityAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
    <ProjectCapability Include="Msix" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.WinUI.UI.Controls.DataGrid" Version="7.1.2" />
    <PackageReference Include="EPPlus" Version="7.4.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.11" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.8" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.26100.4948" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.7.250606001" />
    <PackageReference Include="MySql.Data" Version="9.5.0" />
    <PackageReference Include="MySqlConnector" Version="2.4.0" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.2" />
    <PackageReference Include="QuestPDF" Version="2022.12.15" />
    <PackageReference Include="SkiaSharp" Version="3.119.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PhoneStoreRepository\PhoneStoreRepository.csproj" />
    <ProjectReference Include="..\PhoneStoreServices\PhoneStoreServices.csproj" />
  </ItemGroup>

	<ItemGroup>
	  <Page Update="Theme\Colors.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	  <Page Update="View\BatchesPage.xaml">
	    <SubType>Designer</SubType>
	  </Page>
	  <Page Update="View\PurchaseOrdersPage.xaml">
	    <SubType>Designer</SubType>
	  </Page>
	  <Page Update="View\AddPurchaseOrderPage.xaml">
	    <SubType>Designer</SubType>
	  </Page>
	  <Page Update="View\Controls\NotesInputDialog.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	  <Page Update="View\Controls\SerialNumberInputDialog.xaml">
	    <Generator>MSBuild:Compile</Generator>
      </Page>
	  <Page Update="View\Account\AccountEditPage.xaml">
	    <SubType>Designer</SubType>
	  </Page>
	</ItemGroup>

	<ItemGroup>
	  <None Update="appsettings.json">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <Page Update="View\Controls\InvoiceDialog.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	  <None Update="View\Controls\SerialNumberInputDialog.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </None>
	  <Page Update="View\InvoicePage.Xaml">
	    <Generator>MSBuild:Compile</Generator>
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Page>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Database\" />
	  <Folder Include="Resources\Strings\en-US\" />
	  <Folder Include="View\AddContainers\" />
	</ItemGroup>

  <PropertyGroup Condition="'$(DisableHasPackageAndPublishMenuAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
    <HasPackageAndPublishMenu>true</HasPackageAndPublishMenu>
  </PropertyGroup>

  <!-- Publish Properties -->
  <PropertyGroup>
    <PublishReadyToRun Condition="'$(Configuration)' == 'Debug'">False</PublishReadyToRun>
    <PublishReadyToRun Condition="'$(Configuration)' != 'Debug'">True</PublishReadyToRun>
    <PublishTrimmed Condition="'$(Configuration)' == 'Debug'">False</PublishTrimmed>
    <PublishTrimmed Condition="'$(Configuration)' != 'Debug'">True</PublishTrimmed>
  </PropertyGroup>
  <ItemGroup>
	<PRIResource Update="Resources\Strings\en-US\Resources.resw">
	    <Generator>PublicResXFileCodeGenerator</Generator>
    </PRIResource>
  </ItemGroup>
</Project>
