using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using PhoneStoreAdmin.Models;
using PhoneStoreAdmin.Models.Enums;
using System;
using System.Collections.Generic;
using System.Text;
using System.Globalization;
using System.Linq;

namespace PhoneStoreAdmin.Utils
{
    public class PurchaseOrderPdfGenerator
    {
        public static void GeneratePdf(PurchaseOrder purchaseOrder, Supplier supplier, string filePath)
        {
            if (purchaseOrder == null)
                throw new ArgumentNullException(nameof(purchaseOrder));

            if (supplier == null)
                throw new ArgumentNullException(nameof(supplier));

            if (string.IsNullOrWhiteSpace(filePath))
                throw new ArgumentException("File path cannot be empty", nameof(filePath));

            // Ensure PurchaseOrderLines is never null
            if (purchaseOrder.PurchaseOrderLines == null)
                purchaseOrder.PurchaseOrderLines = new List<PurchaseOrderLine>();

            var productNames = new Dictionary<int, string>();
            try
            {
                var productRepo = App.GetService<Repositories.Interfaces.IProductRepository>();
                if (productRepo != null)
                {
                    foreach (var line in purchaseOrder.PurchaseOrderLines)
                    {
                        if (line == null) continue;

                        if (!productNames.ContainsKey(line.ProductId))
                        {
                            try
                            {
                                var product = productRepo.GetById(line.ProductId);
                                var name = product?.Name ?? $"Product #{line.ProductId}";
                                productNames[line.ProductId] = RemoveVietnamese(name) ?? $"Product #{line.ProductId}";
                            }
                            catch (Exception ex)
                            {
                                Logger.Error($"Failed to get product name for ID {line.ProductId}: {ex.Message}");
                                productNames[line.ProductId] = $"Product #{line.ProductId}";
                            }
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                Logger.Error($"Failed to load product names: {ex.Message}");
                // Continue with empty or partial dictionary
            }

            try
            {
                var document = Document.Create(container =>
                {
                    container.Page(page =>
               {
                   page.Size(PageSizes.A4);
                   page.Margin(2, Unit.Centimetre);
                   page.PageColor(Colors.White);
                   page.DefaultTextStyle(x => x.FontSize(11));

                   page.Header().Element(ComposeHeader);
                   page.Content().Element(c => ComposeContent(c, purchaseOrder, supplier, productNames));
                   page.Footer().AlignCenter().Text("Generated by Phone Store Admin");
               });
                });

                document.GeneratePdf(filePath);
            }
            catch (Exception ex)
            {
                Logger.Error($"Failed to generate PDF: {ex.Message}", ex);
                throw;
            }
        }

        private static string RemoveVietnamese(string text)
        {
            if (string.IsNullOrWhiteSpace(text))
                return text ?? string.Empty;

            try
            {
                // Remove Vietnamese diacritics
                var normalizedString = text.Normalize(NormalizationForm.FormD);
                var stringBuilder = new StringBuilder();

                foreach (var c in normalizedString)
                {
                    var unicodeCategory = CharUnicodeInfo.GetUnicodeCategory(c);
                    if (unicodeCategory != UnicodeCategory.NonSpacingMark)
                    {
                        stringBuilder.Append(c);
                    }
                }

                return stringBuilder.ToString().Normalize(NormalizationForm.FormC);
            }
            catch
            {
                return text;
            }
        }

        private static void ComposeHeader(IContainer container)
        {
            container.Row(row =>
               {
                   row.RelativeItem().Column(column =>
                       {
                           column.Item().Text("PHONE STORE").FontSize(20).Bold().FontColor(Colors.Blue.Darken2);
                           column.Item().Text("Purchase Order").FontSize(16).SemiBold();
                           column.Item().Text("Address: 123 Main St, City").FontSize(9);
                           column.Item().Text("Phone: (123) 456-7890").FontSize(9);
                       });
               });
        }

        private static void ComposeContent(IContainer container, PurchaseOrder purchaseOrder, Supplier supplier, Dictionary<int, string> productNames)
        {
            container.PaddingVertical(20).Column(column =>
        {
            column.Spacing(10);

            column.Item().Row(row =>
            {
                row.RelativeItem().Column(col =>
  {
      col.Item().Text($"PO Number: #{purchaseOrder.Id}").Bold().FontSize(12);
      col.Item().Text($"Order Date: {purchaseOrder.OrderDate:dd/MM/yyyy HH:mm}");
      col.Item().Text($"Status: {GetStatusText(purchaseOrder.Status)}");
  });

                row.RelativeItem().Column(col =>
    {
        col.Item().Text("Supplier Information").Bold().FontSize(12);
        col.Item().Text($"Name: {RemoveVietnamese(supplier?.Name ?? "N/A")}");
  col.Item().Text($"Phone: {supplier?.Phone ?? "N/A"}");
        col.Item().Text($"Email: {RemoveVietnamese(supplier?.Email ?? "N/A")}");
  col.Item().Text($"Address: {RemoveVietnamese(supplier?.Address ?? "N/A")}");
    });
            });

            column.Item().PaddingVertical(5).LineHorizontal(1).LineColor(Colors.Grey.Lighten2);
            column.Item().Text("Order Items").Bold().FontSize(13);

            column.Item().Table(table =>
                   {
                       table.ColumnsDefinition(columns =>
                 {
                     columns.ConstantColumn(30);
                     columns.ConstantColumn(80);
                     columns.RelativeColumn(3);
                     columns.RelativeColumn(1);
                     columns.RelativeColumn(2);
                     columns.RelativeColumn(2);
                 });

                       table.Header(header =>
             {
                 header.Cell().Element(CellStyle).Text("No.").Bold();
                 header.Cell().Element(CellStyle).Text("Product ID").Bold();
                 header.Cell().Element(CellStyle).Text("Product Name").Bold();
                 header.Cell().Element(CellStyle).AlignRight().Text("Qty").Bold();
                 header.Cell().Element(CellStyle).AlignRight().Text("Unit Cost").Bold();
                 header.Cell().Element(CellStyle).AlignRight().Text("Total").Bold();

                 static IContainer CellStyle(IContainer c)
                 {
                     return c.Border(1).BorderColor(Colors.Grey.Lighten1)
       .Background(Colors.Grey.Lighten3).Padding(5);
                 }
             });

                       int index = 1;
                       var lines = purchaseOrder.PurchaseOrderLines?.Where(l => l != null) ?? Enumerable.Empty<PurchaseOrderLine>();
                       foreach (var line in lines)
                       {
                           var productName = productNames.ContainsKey(line.ProductId)
                           ? productNames[line.ProductId]
                        : $"Product #{line.ProductId}";

                           table.Cell().Element(CellStyle).Text(index.ToString());
                           table.Cell().Element(CellStyle).Text($"#{line.ProductId}");
                           table.Cell().Element(CellStyle).Text(productName ?? $"Product #{line.ProductId}");
                           table.Cell().Element(CellStyle).AlignRight().Text(line.Quantity.ToString());
                           table.Cell().Element(CellStyle).AlignRight().Text(FormatCurrency(line.UnitCost));
                           table.Cell().Element(CellStyle).AlignRight().Text(FormatCurrency(line.TotalCost));
                           index++;

                           static IContainer CellStyle(IContainer c)
                           {
                               return c.Border(1).BorderColor(Colors.Grey.Lighten2).Padding(5);
                           }
                       }
                   });

            column.Item().PaddingTop(10).AlignRight().Column(col =>
                    {
                        col.Item().Row(row =>
                   {
                       row.ConstantItem(150).Text("Subtotal:").SemiBold();
                       row.ConstantItem(120).AlignRight().Text(FormatCurrency(purchaseOrder.TotalAmount));
                   });

                        col.Item().Row(row =>
              {
                  row.ConstantItem(150).Text("Tax:").SemiBold();
                  row.ConstantItem(120).AlignRight().Text("0 VND");
              });

                        col.Item().PaddingVertical(2).LineHorizontal(1);

                        col.Item().Row(row =>
            {
                row.ConstantItem(150).Text("Total Amount:").Bold().FontSize(13);
                row.ConstantItem(120).AlignRight().Text(FormatCurrency(purchaseOrder.TotalAmount))
           .Bold().FontSize(13).FontColor(Colors.Blue.Darken2);
            });
                    });

            if (!string.IsNullOrWhiteSpace(purchaseOrder.Note))
            {
                column.Item().PaddingTop(15).Column(col =>
          {
              col.Item().Text("Notes:").Bold();
              col.Item().Border(1).BorderColor(Colors.Grey.Lighten2).Padding(10)
                  .Text(RemoveVietnamese(purchaseOrder.Note) ?? string.Empty);
          });
            }

            column.Item().PaddingTop(30).Row(row =>
               {
                   row.RelativeItem().Column(col =>
                 {
                     col.Item().AlignCenter().Text("Created By").SemiBold();
                     col.Item().PaddingTop(50).AlignCenter().Text("_________________");
                     col.Item().AlignCenter().Text($"User ID: {purchaseOrder.CreatedBy}").FontSize(9);
                 });

                   row.RelativeItem().Column(col =>
{
    col.Item().AlignCenter().Text("Approved By").SemiBold();
    col.Item().PaddingTop(50).AlignCenter().Text("_________________");
    col.Item().AlignCenter().Text("Manager").FontSize(9);
});

                   row.RelativeItem().Column(col =>
               {
                   col.Item().AlignCenter().Text("Received By").SemiBold();
                   col.Item().PaddingTop(50).AlignCenter().Text("_________________");
                   col.Item().AlignCenter().Text("Warehouse Staff").FontSize(9);
               });
               });

            column.Item().PaddingTop(20).AlignCenter()
       .Text($"Generated on: {DateTime.Now:dd/MM/yyyy HH:mm}")
   .FontSize(8).FontColor(Colors.Grey.Medium);
        });
        }

        private static string GetStatusText(PoStatus status)
        {
            return status switch
            {
                PoStatus.DRAFT => "Draft",
                PoStatus.RECEIVED => "Received",
                PoStatus.CANCELLED => "Cancelled",
                _ => "Unknown"
            };
        }

        private static string FormatCurrency(decimal amount)
        {
            return $"{amount:N0} VND";
        }
    }
}
